function [fitresult, gof] = createFits(x1, SARD1GSNO, SARD1Control, x2, C438SGSNO, C438SControl)
%CREATEFITS1(X1,SARD1GSNO,SARD1CONTROL,X2,C438SGSNO,C438SCONTROL)
%  Create fits.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x1
%      Y Output: SARD1GSNO
%  Data for 'untitled fit 2' fit:
%      X Input : x1
%      Y Output: SARD1Control
%  Data for 'untitled fit 3' fit:
%      X Input : x2
%      Y Output: C438SGSNO
%  Data for 'untitled fit 4' fit:
%      X Input : x2
%      Y Output: C438SControl
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Sep-2018 22:08:26

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 4, 1 );
gof = struct( 'sse', cell( 4, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x1, SARD1GSNO );

% Set up fittype and options.
ft = fittype( '(a*x^1)/(k^1+x^1)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.294335059579541 0.532907526979309];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'SARD1GSNO vs. x1', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel x1
ylabel SARD1GSNO
grid on

%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( x1, SARD1Control );

% Set up fittype and options.
ft = fittype( '(a*x^1)/(k^1+x^1)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.400315608286272 0.702000864717242];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'SARD1Control vs. x1', 'untitled fit 2', 'Location', 'NorthEast' );
% Label axes
xlabel x1
ylabel SARD1Control
grid on

%% Fit: 'untitled fit 3'.
[xData, yData] = prepareCurveData( x2, C438SGSNO );

% Set up fittype and options.
ft = fittype( '(a*x^1)/(k^1+x^1)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.260346914517245 0.917519033145336];

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 3' );
h = plot( fitresult{3}, xData, yData );
legend( h, 'C438SGSNO vs. x2', 'untitled fit 3', 'Location', 'NorthEast' );
% Label axes
xlabel x2
ylabel C438SGSNO
grid on

%% Fit: 'untitled fit 4'.
[xData, yData] = prepareCurveData( x2, C438SControl );

% Set up fittype and options.
ft = fittype( '(a*x^1)/(k^1+x^1)', 'independent', 'x', 'dependent', 'y' );
excludedPoints = excludedata( xData, yData, 'Indices', 8 );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.503130903209796 0.378475789267472];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult{4}, gof(4)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 4' );
h = plot( fitresult{4}, xData, yData, excludedPoints );
legend( h, 'C438SControl vs. x2', 'Excluded C438SControl vs. x2', 'untitled fit 4', 'Location', 'NorthEast' );
% Label axes
xlabel x2
ylabel C438SControl
grid on


