%this script depends on the data generated by the experimentqueryplotting
%hxts script, which generates botht eh meandata and the celldata objects
%used here.

nms=fieldnames(meandata)
mat=[];
gv=[]
c=1;
for j=1:numel(nms)
    
    m=meandata.(nms{j}).g1percent;
    for k=1:size(m, 1)
        gv{c}= nms{j};
        mat(c, :)=m(k,:); 
        c=c+1;
    end
   
end

getformat= @(strain) {'MarkerEdgeColor',straincolors(strcmp(strains, strain),:),  'Marker', '.', 'MarkerSize', 14}
groupformats=arrayfun(getformat, unique(gv), 'UniformOutput', false)

[coeff, scores]= princomp(mat)
figure; 
h=biplotG(coeff, scores, 'Groups', gv, 'Format', groupformats)

save2pdf('/Users/s1259407/Google Drive/0AFigures/paper/20180704_HXTPCA.pdf')    
%format array for hxts


    

%work with cell traces
nms=fieldnames(celldata)
matcells=[];
gv=[];
c=1;
for j=1:numel(nms)
    
    m=celldata.(nms{j}).g1percent.rep1;
    for k=1:size(m, 1)
        gv{c}= nms{j};
        matcells(c, :)=m(k,:); 
        c=c+1;
    end
   
end

%can use 2 colormaps. 
%straincolors which was made by me (in the experimentqueryplottingHXTs
%script
%straincolors2 which comes from colorbrewer set 3
straincolors2=brewermap(7,'Set3')
getformat= @(strain) {'MarkerEdgeColor',straincolors(strcmp(strains, strain),:),  'Marker', '.', 'MarkerSize', 6}
groupformats=arrayfun(getformat, unique(gv), 'UniformOutput', false)

[coeffs, scoress]= princomp(matcells);
figure; 
comp=[1,2];
h3=biplotG(coeffs(:, comp), scoress(:, comp), 'Groups', gv, 'Format', groupformats)
xlabel(['Component ' num2str(comp(1))])
ylabel(['Component ' num2str(comp(2))])
title('PCA of cell traces')
ylim([-.06, .06])
xlim([-.05, .1])
%ylim([-.1, .1])
%xlim([-.06, .1])
save2pdf('/Users/s1259407/Google Drive/0AFigures/paper/20180704_HXTPCAcells.pdf')    



groupformats=arrayfun(getformat, gv, 'UniformOutput', false)
[coeffs, scores]= princomp(matcells);

figure; h3=biplotG(coeffs(:, comp), scores(:, comp), 'Groups', gv)
save2pdf('/Users/s1259407/Google Drive/0AFigures/paper/20180704_HXTPCA.pdf')
    