function [coeffs, scores, yArray, groupVector]=  PCAworkflow(yArray,components, varargin)
%%yArray is from an outcome of the function exploreparam or
%%exploreparamcomb (out.y) which is a rownumber signals and columnumber timepoints,
%%generated by a model aimed at matching the references varargin. each
%%reference is a signal of 1X columnumber timepoints. each of these
%%references %%will be scaled several times and all those scalings will be
%%put together %%into a big matrix. then a grouping vector will be created
%%such that the number of each entry indicates what group the row belongs
%%to. this is useful for labelledPCA. 

%%%comps could default to [1,2]
groupVector= ones(size(yArray, 1),1)

yArray= normalizeTS(yArray);
for j= 1: numel(varargin)
    
    %add the scalings of reference j to yArray
    yArray= [yArray;  [normalizeTS(varargin{j})'*[.0001:.005:1]]'];
    groupVector= [groupVector; ones(size([normalizeTS(varargin{j})'*[.0001:.005:1]]', 1),1)* (j-2)]
    
end



 figure; 
 [coeffs, scores]= labelledPCA(yArray, groupVector, components);
 
end
    
    
    



